import { createMascotPerformanceAdapter } from './mascotPerformanceAdapter';

export const foxyPerformanceAdapter = createMascotPerformanceAdapter({
  id: 'foxy-v3',
  base: {
    bodyY: 0,
    bodyLean: 0,
    headY: 0,
    headTilt: 0,
    leftHandX: -112,
    leftHandY: 58,
    rightHandX: 112,
    rightHandY: 58,
    eyeScale: 1,
    browY: 0,
    smileOpacity: 0.02,
    neutralOpacity: 1,
    frownOpacity: 0,
    expressionMouthOpacity: 0,
    tearOpacity: 0,
    sparkleOpacity: 0,
    blushOpacity: 0.7,
    browTilt: 0,
    tailTilt: 0,
  },
  // Keep visible movement compact; the new arm art hides the skeleton and relies
  // on overlapping skin shapes rather than exposed elbow/paw joints.
  armX: 58,
  armY: 118,
  bodyLift: 17,
  bodyLean: 0.05,
  headLift: 14,
  headTilt: 0.17,
  eyeScale: 0.24,
  browLift: 10,
  browTilt: 0.9,
  tailTilt: 0.46,
  thinkHandX: -58,
  thinkHandY: -106,
  motionCharacter: 'nimble',
  emotion: {
    calm: { smileOpacity: 0.02, neutralOpacity: 1, blushOpacity: 0.68 },
    happy: { smileOpacity: 0.62, neutralOpacity: 0.08, eyeScale: -0.13, blushOpacity: 0.9, tailTilt: 0.14 },
    curious: { eyeScale: 0.08, browY: -2, headTilt: -0.035, browTilt: 0.12 },
    excited: { smileOpacity: 0.68, neutralOpacity: 0.04, eyeScale: 0.05, blushOpacity: 1, tailTilt: 0.2 },
  },
});
